/* -*- c++ -*- */
/*
 * Copyright 2004,2010 Free Software Foundation, Inc.
 * 
 * This file is part of GNU Radio
 * 
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <chaos_gen_logi_map_f.h>
#include <gr_io_signature.h>

/*
 * Create a new instance of chaos_gen_logi_map_f and return
 * a boost shared_ptr.  This is effectively the public constructor.
 */
chaos_gen_logi_map_f_sptr 
chaos_make_gen_logi_map_f(float seed)
{
  return gnuradio::get_initial_sptr(new chaos_gen_logi_map_f(seed));
}

/*
 * Specify constraints on number of input and output streams.
 * This info is used to construct the input and output signatures
 * (2nd & 3rd args to gr_block's constructor).  The input and
 * output signatures are used by the runtime system to
 * check that a valid number and type of inputs and outputs
 * are connected to this block.
 */
static const int MIN_IN = 0;	// mininum number of input streams
static const int MAX_IN = 0;	// maximum number of input streams
static const int MIN_OUT = 1;	// minimum number of output streams
static const int MAX_OUT = 1;	// maximum number of output streams

/*
 * The private constructor
 */
chaos_gen_logi_map_f::chaos_gen_logi_map_f (float seed)
  : gr_sync_block ("gen_logi_map_f",
                   gr_make_io_signature (MIN_IN, MAX_IN, 0),
                   gr_make_io_signature (MIN_OUT, MAX_OUT, sizeof (float))),
    d_seed (seed)
{	
  next_val = d_seed;
}

/*
 * Our virtual destructor.
 */
chaos_gen_logi_map_f::~chaos_gen_logi_map_f()
{
}

float
chaos_gen_logi_map_f::gen_next_chaos()
{
  float val;

  val = next_val;
  next_val = 1.0 - 2.0 * (val * val);

  return (val);
}

int 
chaos_gen_logi_map_f::work (int noutput_items,
                            gr_vector_const_void_star &input_items,
                            gr_vector_void_star &output_items)
{				
  float *out_samples = (float *) output_items[0];
  int i;

  for (i = 0; i < noutput_items; i++) {
    out_samples[i] = gen_next_chaos();
  }

  return (noutput_items);
}
